# Generated by Django 6.0.3 on 2026-03-15 04:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('dept_type', models.CharField(choices=[('icu', 'ICU'), ('emergency', 'Emergency'), ('general', 'General Ward'), ('surgery', 'Surgery'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('pediatrics', 'Pediatrics'), ('oncology', 'Oncology'), ('orthopedic', 'Orthopedics'), ('radiology', 'Radiology'), ('pathology', 'Pathology'), ('other', 'Other')], default='other', max_length=20)),
                ('floor', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('trust', 'Trust'), ('trauma', 'Trauma Center')], max_length=20)),
                ('hospital_type', models.CharField(choices=[('multispecialty', 'Multispecialty'), ('specialty', 'Specialty'), ('clinic', 'Clinic')], max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('total_beds', models.PositiveIntegerField(default=0)),
                ('icu_capacity', models.PositiveIntegerField(default=0)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hospitals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'service_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('registration_no', models.CharField(max_length=50, unique=True)),
                ('specialization', models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('oncology', 'Oncology'), ('pediatrics', 'Pediatrics'), ('general', 'General Medicine'), ('surgery', 'Surgery'), ('radiology', 'Radiology'), ('emergency', 'Emergency Medicine'), ('icu', 'Intensive Care'), ('nephrology', 'Nephrology'), ('other', 'Other')], max_length=30)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='hospitals.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='hospitals.hospital')),
            ],
            options={
                'db_table': 'doctors',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='DutySchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift_type', models.CharField(choices=[('morning', 'Morning  (6am–2pm)'), ('evening', 'Evening  (2pm–10pm)'), ('night', 'Night    (10pm–6am)'), ('full_day', 'Full Day (24hr)'), ('custom', 'Custom')], max_length=20)),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_schedules', to='hospitals.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_schedules', to='hospitals.doctor')),
            ],
            options={
                'db_table': 'duty_schedules',
                'ordering': ['shift_start'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='hospitals.hospital'),
        ),
        migrations.CreateModel(
            name='HospitalRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('license_document', models.FileField(blank=True, null=True, upload_to='hospital_docs/')),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='hospitals.hospital')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_hospitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hospital_registrations',
            },
        ),
        migrations.CreateModel(
            name='ServiceMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hospitals.servicecategory')),
            ],
            options={
                'db_table': 'service_master',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('hospital', 'name')},
        ),
        migrations.CreateModel(
            name='HospitalService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hospitals.hospital')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_services', to='hospitals.servicemaster')),
            ],
            options={
                'db_table': 'hospital_services',
                'unique_together': {('hospital', 'service')},
            },
        ),
    ]
