# Generated by Django 6.0.3 on 2026-03-15 04:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beds', '0001_initial'),
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('bed_long_occupancy', 'Bed Long Occupancy'), ('resource_mismatch', 'Resource Mismatch'), ('data_inconsistency', 'Data Inconsistency'), ('hospital_verification_due', 'Hospital Verification Due'), ('suspicious_bed_pattern', 'Suspicious Bed Pattern'), ('missing_data', 'Missing Data'), ('transfer_delay', 'Transfer Delay'), ('equipment_maintenance_due', 'Equipment Maintenance Due')], max_length=40)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('meta_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='beds.bed')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='hospitals.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='hospitals.hospital')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('bed', 'Bed'), ('ventilator', 'Ventilator'), ('icu_bed', 'ICU Bed'), ('oxygen', 'Oxygen'), ('blood', 'Blood'), ('equipment', 'Equipment')], max_length=20)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('available_count', models.PositiveIntegerField(default=0)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('limited', 'Limited')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_snapshots', to='hospitals.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_snapshots', to='hospitals.hospital')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resource_availability',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
