# Generated by Django 6.0.3 on 2026-03-15 04:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('ambulance_type', models.CharField(choices=[('basic', 'Basic Life Support'), ('advanced', 'Advanced Life Support'), ('icu', 'ICU Ambulance'), ('neonatal', 'Neonatal'), ('mortuary', 'Mortuary')], max_length=20)),
                ('driver_name', models.CharField(max_length=150)),
                ('driver_phone', models.CharField(max_length=15)),
                ('driver_license', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive')], default='available', max_length=20)),
                ('trips_completed', models.PositiveIntegerField(default=0)),
                ('service_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ambulances',
                'ordering': ['city', 'ambulance_type'],
            },
        ),
        migrations.CreateModel(
            name='AmbulanceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_address', models.TextField()),
                ('pickup_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_city', models.CharField(max_length=100)),
                ('ambulance_type', models.CharField(choices=[('basic', 'Basic Life Support'), ('advanced', 'Advanced Life Support'), ('icu', 'ICU Ambulance'), ('neonatal', 'Neonatal'), ('mortuary', 'Mortuary')], default='basic', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('en_route', 'En Route to Patient'), ('picked_up', 'Patient Picked Up'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('source', models.CharField(choices=[('patient', 'Patient Portal'), ('reception', 'Reception Portal')], default='patient', max_length=20)),
                ('requester_name', models.CharField(max_length=150)),
                ('requester_phone', models.CharField(max_length=15)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('response_time_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('trip_duration_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('patient_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ambulance_requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
