# Generated by Django 6.0.3 on 2026-03-15 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambulances', '0001_initial'),
        ('hospitals', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='driver',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'ambulance'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambulances', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='ambulancerequest',
            name='ambulance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='ambulances.ambulance'),
        ),
        migrations.AddField(
            model_name='ambulancerequest',
            name='destination_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_requests', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='ambulancerequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_requests', to='patients.patient'),
        ),
    ]
