# Generated by Django 6.0.3 on 2026-03-15 07:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_type', models.CharField(choices=[('transfer_notification', 'Transfer Notification'), ('user_agent', 'User AI Agent')], max_length=30)),
                ('to_number', models.CharField(max_length=20)),
                ('twilio_call_sid', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('no_answer', 'No Answer')], default='initiated', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], default='en', max_length=5)),
                ('duration_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transfer_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='patients.transferrequest')),
            ],
            options={
                'db_table': 'call_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('twilio_call_sid', models.CharField(db_index=True, max_length=50)),
                ('language', models.CharField(default='en', max_length=5)),
                ('conversation_history', models.JSONField(default=list)),
                ('detected_intent', models.CharField(blank=True, max_length=50, null=True)),
                ('user_city', models.CharField(blank=True, max_length=100, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='calls.calllog')),
            ],
            options={
                'db_table': 'call_sessions',
            },
        ),
    ]
