# Generated by Django 6.0.3 on 2026-03-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
